### ISSUE TITLE
Broken support with iOS 9?

### ISSUE THREAD

**Issue by batlounis** [Musixmatchdev/musixmatch-app-extension#1]
Hi,
We integrated Musixmatch with Anghami, but it seems after iOS 9, each time I tap to see lyrics from Anghami, I get an alert to get Musixmatch app. Any ideas?

**Comment by loretoparisi** [comment]
Thanks for reporting @batlounis we are going to provide a fix as soon as possible.
In the meanwhile, I suppose that this issue could be due to new iOS9.0 limitations on openURL.
Please add the following keys to your `Info.plist`

``` xml
<key>LSApplicationQueriesSchemes</key>
    <array>
        <string>mxm</string>
 </array>
```

**Comment by martinobonfiglioli** [comment]
As mention by @loretoparisi with iOS9 you need to declare the URL schemes used in your app inside your Info.plist.
I pushed a new version, now the example works great.
Check it out!
